[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"

[project]
name = "scim2-flask"
version = "0.0.0"
description = "Painless SCIM integration for Flask"
readme = "README.md"
authors = [
    { name = "Éloi Rivard", email = "eloi@yaal.coop" }
]
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.3",
    "scim2-models>=0.7.0",
]

[dependency-groups]
dev = [
    "httpx2>=0.27",
    "pytest>=8.0",
    "scim2-tester>=0.2.8",
]

[tool.pytest.ini_options]
pythonpath = ["."]
